apiVersion: v1
kind: Service
metadata:
  name: arks-gateway-plugins
  namespace: arks-operator-system
  labels:
    app: arks-gateway-plugins
spec:
  selector:
    app: arks-gateway-plugins
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: grpc
    - name: metrics
      protocol: TCP
      port: 9110
      targetPort: metrics
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arks-gateway-plugins
  namespace: arks-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arks-gateway-plugins
  namespace: arks-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arks-gateway-plugins
  template:
    metadata:
      labels:
        app: arks-gateway-plugins
    spec:
      initContainers:
        - name: init-c
          image: busybox:1.37.0
          command: ['sh', '-c', 'until echo "ping" | nc arks-redis-master 6379 -w 1  | grep -c PONG; do echo waiting for service arks-redis-master; sleep 2; done']
      containers:
        - name: main
          # TODO: image update
          image: scitixai/arks-gateway-plugins:v0.1.8
          imagePullPolicy: Always
          args:
            - -redis.addrs=arks-redis-master:6379
          ports:
            - name: grpc
              containerPort: 50052
            - name: metrics
              containerPort: 9110
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: arks-gateway-plugins
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: arks-gateway-http-router
  namespace: arks-operator-system
spec:
  parentRefs:
    - name: arks-eg
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/models
      backendRefs:
        - name: arks-gateway-plugins
          port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: skip-ext-proc
  namespace: arks-operator-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: arks-gateway-http-router
---
# this is a dummy route for incoming request and,
# then request is routed to httproute using model name OR
# request is routed based on the target for that model service
# TODO (varun): check if this dummy route can be removed in future
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: arks-reserved-router
  namespace: arks-operator-system
spec:
  parentRefs:
    - name: arks-eg
  rules:
    # TODO: match method
    - matches:
        - path:
            type: PathPrefix
            value: /v1/chat/completions
        - path:
            type: PathPrefix
            value: /v1/completions

      # FIX: remove this 
      # backendRefs:
      #   - name: arks-gateway-plugins
      #     port: 50052
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: gateway-plugins-extension-policy
  namespace: arks-operator-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: arks-eg
    # FIX: use gateway instead of HTTPRoute?
    # group: gateway.networking.k8s.io
    # kind: HTTPRoute
    # name: arks-reserved-router
  extProc:
    - backendRefs:
        - name: arks-gateway-plugins
          port: 50052
      processingMode:
        request:
          body: Buffered
        response: 
          body: Streamed
      messageTimeout: 5s
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: healthcheck
  namespace: arks-operator-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: arks-eg
  healthCheck:
    passive:
      baseEjectionTime: 30s
      consecutive5XxErrors: 3
      consecutiveGatewayErrors: 3
      consecutiveLocalOriginFailures: 3
      interval: 30s
      maxEjectionPercent: 100
      splitExternalLocalOriginErrors: false